# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: false
cache: packages

env:
  - WARMUPPKGS='checkmate backports'

jobs:
  include:
    - stage: warmup
      install: Rscript -e 'install.packages(trimws(strsplit(Sys.getenv("WARMUPPKGS", " "))[[1]]))'
      script: true
    - stage: check
