# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: false
cache: packages
latex: false

jobs:
  include:
    - stage: warmup
      env:
        - WARMUPPKGS='checkmate backports'
      install: Rscript -e 'install.packages(trimws(strsplit(Sys.getenv("WARMUPPKGS"), " ")[[1]]))'
      script: true
    - stage: check
