# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: false
cache: packages
latex: false

jobs:
  include:
    - stage: warmup
      env:
        - WARMUPPKGS='checkmate backports'
      install: 
        - Rscript -e 'pkgs = trimws(strsplit(Sys.getenv("WARMUPPKGS"), " ")[[1]]); pkgs = pkgs[!pkgs %in% installed.packages()]; if (length(pkgs) > 0) install.packages(pkgs, repos = "https://cloud.r-project.org"])'
      script: true
    - stage: check
