# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
    - stage: warmup
      script: Rscript -e 'install.packages("checkmate")'
    - stage: check
